### ISSUE TITLE
GetMilliseconds()

### ISSUE THREAD

**Issue by JRVeale** [fbiego/ESP32Time#1]
Nice wrapper library!

I see there's no GetMilliseconds() function. Seeing as the user can input ms when setting the current time, it would be nice to be able to get the ms out as well.

Is this possible? Thanks

**Comment by fbiego** [comment]
Updated
commit [8c6d08d](https://github.com/fbiego/ESP32Time/commit/8c6d08d78cfbdfa12001710deb3f71400d531771)

**Comment by JRVeale** [comment]
```
long ESP32Time::getMillis(){
	struct timeval tv;
	gettimeofday(&tv, NULL);
	return tv.tv_sec;
}
```

Shouldn't the return value be `tv.tv_usec`/1000?

Edit: i got milliseconds and microseconds mixed up

Edit2: This confusion stems from your wrapper using ms to mean microseconds rather than milliseconds. Perhaps it is more suitable to have a getMicroseconds() function rather than a getMilliseconds() function?

**Comment by fbiego** [comment]
the function above returns the epoch seconds
I've made the following changes;
- getEpoch() `return tv.tv_sec`
- getMillis() `return tv.tv_usec/1000`
- getMicros() `return tv.tv_usec`
