### ISSUE TITLE
error compliling

### ISSUE THREAD

**Issue by kang2k10** [fbiego/ESP32Time#11]
Hello. With compiling example, some errors

error: variable 'tm timeinfo' has initializer but incomplete type
   struct tm timeinfo = rtc.getTimeStruct();
error: invalid use of incomplete type 'struct tm'
   struct tm timeinfo = rtc.getTimeStruct();

How fix that ?

**Comment by fbiego** [comment]
is this on the Arduino IDE?

**Comment by kang2k10** [comment]
yes. Arduino IDE v1.8.13, esp32 core 2.0.0

**Comment by fbiego** [comment]
what libraries have you included in your code?

**Comment by kang2k10** [comment]
only one "ESP32Time.h"
i compilling example from library
if i change esp32 core to 1.0.6, compilling with out errors

**Comment by brownrb** [comment]
add this at the top
#include "time.h"

**Comment by kang2k10** [comment]
Thanks. Is good solutions!
