### ISSUE TITLE
Adjust time accuracy 

### ISSUE THREAD

**Issue by luke2023** [fbiego/ESP32Time#20]
hello,everything goes well!Thank you for the library! Since i have a 5min delay every day, do you plan to add a function to adjust accuracy like (original time)+( delta time)x0.003? or we can modify the original rtc source ,thank you !

^_^
lin che

**Comment by fbiego** [comment]
The rtc is not accurate and will either gain or lose time. This change is not the same for every chip therefore the function will not be useful for some.

If you know the time change, you can set it as follows
`rtc.setTime(rtc.getEpoch() + changeInSeconds);`

**Comment by luke2023** [comment]
@fbiego thank you!I'll  try it.
