### ISSUE TITLE
Offset is unsigned

### ISSUE THREAD

**Issue by gonzabrusco** [fbiego/ESP32Time#23]
Hello. Not sure if this is a bug or not. The offset type was originally signed long, but now you changed it to unsigned long. Is that correct? How do I set a GMT -3 ?

Thanks
Gonzalo

**Comment by gonzabrusco** [comment]
Nevermind, not really sure why, but it worked nevertheless. Probably just a matter of unit interpretation.

**Comment by 06GitHub** [comment]
```
ESP32Time rtc(0);
...
rtc.offset=-3600; // negative offset
```
works for me
