### ISSUE TITLE
What is the best way to use NTP in this library?

### ISSUE THREAD

**Issue by rtek1000** [fbiego/ESP32Time#25]
Hello,

I managed to use NTP with the help of this other library:

https://github.com/arduino-libraries/NTPClient

`rtc.setTime(timeClient.getEpochTime());`

**Comment by hpsaturn** [comment]
You don't need libraries on ESP32 to handle the NTP requests. The Arduino Framework (Espressiff), is built with this support and internal libraries. For example I did this eInk clock using it 3 years ago:

https://github.com/hpsaturn/m5coreink-ntp-clock
