### ISSUE TITLE
Missing initializer for member "overflow"

### ISSUE THREAD

**Issue by Nanowires** [fbiego/ESP32Time#27]
Hi,

I'm using the IDE sloeber and get the compiler warning:
`Member 'overflow' was not initialized in this constructor`

Also when I'm using the library, the overflow is always true (remark: uninitialized variables are random, bool is using an uint8_t I guess, so 254 of 255 cases).

Fix would be to explicitly initialize the value of overflow in the constructor.

In your defence, it semms like the Arduino IDE compiler will automatically initialize primitive types, but it's not specified behaviour and should be avoided ;-)

Thanks

**Comment by fbiego** [comment]
Can you create a pr with the changes?

**Comment by Nanowires** [comment]
Please see  #28

**Comment by Nanowires** [comment]
This was fast and easy 😲 👍
