### ISSUE TITLE
If a date after 2036 is set by mistake, the correct date cannot be reset

### ISSUE THREAD

**Issue by lovyan03** [fbiego/ESP32Time#30]
Hello! Thanks for publishing this library.

I noticed that if I setTime for a date after 2036 by mistake, the overflow flag is not cleared even if I set the correct date again.
In this case, the system must be reset to restore it.
Is it necessary to set `this->overflow = false` in a line97 within the setTime function?

https://github.com/fbiego/ESP32Time/blob/548dfd385c961589aa95384a689422c0481283c7/ESP32Time.cpp#L93-L98

Again thank you for your work.

**Comment by fbiego** [comment]
thanks for pointing this out, yes it would be necessary to reset the overflow flag
