### ISSUE TITLE
getDate() format

### ISSUE THREAD

**Issue by caiovernaglia** [fbiego/ESP32Time#41]
It would be interesting to have an option to display the date in YYYY/MM/DD format.
Currently, we only have the option that displays with the day of the week.

**Comment by fbiego** [comment]
you can use getTime("") and specify the format you want by passing it as a string. 
Check here 
https://cplusplus.com/reference/ctime/strftime/

for YYYY/MM/DD you would pass the format as
`getTime("%Y/%m/%d");`
