### ISSUE TITLE
Lost Time

### ISSUE THREAD

**Issue by ebelouet** [fbiego/ESP32Time#6]
HI,

You example work very well but I have 6 minutes more in one day, where is mistake ?

Sincerely
Eric

**Comment by fbiego** [comment]
The internal RTC is not accurate
> Internal RTC clock frequency error is about 5%

It is recommended you set/sync the time periodically

**Comment by ebelouet** [comment]
thank, best way  is to put external crysral, but your example takie it to run.

Sincerely
Eric

**Comment by ebelouet** [comment]
Hi,
Add external crystal option will be good for your library ....to have a  vervy good time solution

**Comment by fbiego** [comment]
the clock source cannot be changed.
[arduino-esp32/issues/3964](https://github.com/espressif/arduino-esp32/issues/3964)
to change it the `arduino-esp32` library has to be recompiled
