### ISSUE TITLE
setTime from tm

### ISSUE THREAD

**Issue by jcherrabi** [fbiego/ESP32Time#8]
hello i added a function to set the time from a time struct tm which is usefull when you get time from an NPT server.

add this to ESP32Time.cpp
`
void ESP32Time::setTimeStruct(tm t)
{
	time_t timeSinceEpoch = mktime(&t);
	setTime(timeSinceEpoch, 0);
}
`
and ESPTime.h
`
void setTimeStruct(tm t);
`
usage:
`
    /* ----------------------------Initialize and get NPT Time-------------------------- */
    configTime(gmtOffset_sec, daylightOffset_sec, ntpServer);
struct tm timeinfo;
if (getLocalTime(&timeinfo))
{
  rtc.setTimeStruct(timeinfo);
}`

Hope this helps!

**Comment by fbiego** [comment]
great, just fork the repo, make the changes then create a PR
